# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cohorts_get(self):
        """Test case for cohorts_get

        """
        pass

    def test_cohorts_uuid_get(self):
        """Test case for cohorts_uuid_get

        """
        pass

    def test_internships_get(self):
        """Test case for internships_get

        """
        pass

    def test_internships_uuid_get(self):
        """Test case for internships_uuid_get

        """
        pass

    def test_masters_allocations_get(self):
        """Test case for masters_allocations_get

        """
        pass

    def test_masters_allocations_uuid_get(self):
        """Test case for masters_allocations_uuid_get

        """
        pass

    def test_masters_get(self):
        """Test case for masters_get

        """
        pass

    def test_masters_uuid_activate_account_put(self):
        """Test case for masters_uuid_activate_account_put

        """
        pass

    def test_masters_uuid_get(self):
        """Test case for masters_uuid_get

        """
        pass

    def test_organizations_get(self):
        """Test case for organizations_get

        """
        pass

    def test_organizations_uuid_get(self):
        """Test case for organizations_uuid_get

        """
        pass

    def test_periods_get(self):
        """Test case for periods_get

        """
        pass

    def test_periods_uuid_get(self):
        """Test case for periods_uuid_get

        """
        pass

    def test_specialties_get(self):
        """Test case for specialties_get

        """
        pass

    def test_specialties_uuid_get(self):
        """Test case for specialties_uuid_get

        """
        pass

    def test_students_affectations_get(self):
        """Test case for students_affectations_get

        """
        pass

    def test_students_affectations_uuid_get(self):
        """Test case for students_affectations_uuid_get

        """
        pass

    def test_students_get(self):
        """Test case for students_get

        """
        pass

    def test_students_uuid_get(self):
        """Test case for students_uuid_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
