"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.15
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_internship_sdk
from osis_internship_sdk.model.first_choice_get import FirstChoiceGet
globals()['FirstChoiceGet'] = FirstChoiceGet
from osis_internship_sdk.model.first_choice_paging import FirstChoicePaging


class TestFirstChoicePaging(unittest.TestCase):
    """FirstChoicePaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirstChoicePaging(self):
        """Test FirstChoicePaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FirstChoicePaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
