"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_internship_sdk
from osis_internship_sdk.model.specialty_get import SpecialtyGet
from osis_internship_sdk.model.student_get import StudentGet
globals()['SpecialtyGet'] = SpecialtyGet
globals()['StudentGet'] = StudentGet
from osis_internship_sdk.model.choice_get import ChoiceGet


class TestChoiceGet(unittest.TestCase):
    """ChoiceGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChoiceGet(self):
        """Test ChoiceGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChoiceGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
