"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_internship_sdk
from osis_internship_sdk.model.offer_get import OfferGet
globals()['OfferGet'] = OfferGet
from osis_internship_sdk.model.offer_paging import OfferPaging


class TestOfferPaging(unittest.TestCase):
    """OfferPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOfferPaging(self):
        """Test OfferPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OfferPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
