# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from models.allocation_get import AllocationGet  # noqa: E501
from rest import ApiException


class TestAllocationGet(unittest.TestCase):
    """AllocationGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocationGet(self):
        """Test AllocationGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis_internship_sdk.models.allocation_get.AllocationGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
