# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.master_get import MasterGet  # noqa: E501
from openapi_client.rest import ApiException


class TestMasterGet(unittest.TestCase):
    """MasterGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMasterGet(self):
        """Test MasterGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = internship-sdk.models.master_get.MasterGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
