# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from models.student import Student  # noqa: E501
from rest import ApiException


class TestStudent(unittest.TestCase):
    """Student unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudent(self):
        """Test Student"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis_internship_sdk.models.student.Student()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
