# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1.0.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import osis_internship_sdk
from osis_internship_sdk.models.inline_response404 import InlineResponse404  # noqa: E501
from osis_internship_sdk.rest import ApiException


class TestInlineResponse404(unittest.TestCase):
    """InlineResponse404 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse404(self):
        """Test InlineResponse404"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis_internship_sdk.models.inline_response404.InlineResponse404()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
