# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from models.organization_get import OrganizationGet  # noqa: E501
from rest import ApiException


class TestOrganizationGet(unittest.TestCase):
    """OrganizationGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationGet(self):
        """Test OrganizationGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis-internship-sdk.models.organization_get.OrganizationGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
