# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.cohort_get import CohortGet  # noqa: E501
from openapi_client.rest import ApiException


class TestCohortGet(unittest.TestCase):
    """CohortGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCohortGet(self):
        """Test CohortGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = internship-sdk.models.cohort_get.CohortGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
