"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_internship_sdk
from osis_internship_sdk.model.internship_choice_create_command import InternshipChoiceCreateCommand


class TestInternshipChoiceCreateCommand(unittest.TestCase):
    """InternshipChoiceCreateCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternshipChoiceCreateCommand(self):
        """Test InternshipChoiceCreateCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InternshipChoiceCreateCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
