# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from models.specialty_get import SpecialtyGet  # noqa: E501
from rest import ApiException


class TestSpecialtyGet(unittest.TestCase):
    """SpecialtyGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecialtyGet(self):
        """Test SpecialtyGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis-internship-sdk.models.specialty_get.SpecialtyGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
