# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from models.period_get import PeriodGet  # noqa: E501
from rest import ApiException


class TestPeriodGet(unittest.TestCase):
    """PeriodGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeriodGet(self):
        """Test PeriodGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = osis_internship_sdk.models.period_get.PeriodGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
