# coding: utf-8

# flake8: noqa

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
# import models into sdk package
from openapi_client.models.allocation_get import AllocationGet
from openapi_client.models.cohort_get import CohortGet
from openapi_client.models.country import Country
from openapi_client.models.internship_get import InternshipGet
from openapi_client.models.master_get import MasterGet
from openapi_client.models.organization_get import OrganizationGet
from openapi_client.models.paging import Paging
from openapi_client.models.period_get import PeriodGet
from openapi_client.models.person import Person
from openapi_client.models.specialty_get import SpecialtyGet
from openapi_client.models.student import Student
from openapi_client.models.student_affectation_get import StudentAffectationGet
from openapi_client.models.student_get import StudentGet
