# coding: utf-8

# flake8: noqa
"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1.0.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from osis_internship_sdk.models.allocation_get import AllocationGet
from osis_internship_sdk.models.cohort_get import CohortGet
from osis_internship_sdk.models.country import Country
from osis_internship_sdk.models.inline_response404 import InlineResponse404
from osis_internship_sdk.models.internship_get import InternshipGet
from osis_internship_sdk.models.master_get import MasterGet
from osis_internship_sdk.models.organization_get import OrganizationGet
from osis_internship_sdk.models.paging import Paging
from osis_internship_sdk.models.period_get import PeriodGet
from osis_internship_sdk.models.person import Person
from osis_internship_sdk.models.score_get import ScoreGet
from osis_internship_sdk.models.specialty_get import SpecialtyGet
from osis_internship_sdk.models.student import Student
from osis_internship_sdk.models.student_affectation_get import StudentAffectationGet
from osis_internship_sdk.models.student_get import StudentGet
