# coding: utf-8

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ScoreGet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'student': 'Student',
        'period': 'PeriodGet',
        'cohort': 'CohortGet',
        'excused': 'bool',
        'reason': 'str',
        'score': 'float'
    }

    attribute_map = {
        'uuid': 'uuid',
        'student': 'student',
        'period': 'period',
        'cohort': 'cohort',
        'excused': 'excused',
        'reason': 'reason',
        'score': 'score'
    }

    def __init__(self, uuid=None, student=None, period=None, cohort=None, excused=None, reason=None, score=None):  # noqa: E501
        """ScoreGet - a model defined in OpenAPI"""  # noqa: E501

        self._uuid = None
        self._student = None
        self._period = None
        self._cohort = None
        self._excused = None
        self._reason = None
        self._score = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if student is not None:
            self.student = student
        if period is not None:
            self.period = period
        if cohort is not None:
            self.cohort = cohort
        if excused is not None:
            self.excused = excused
        if reason is not None:
            self.reason = reason
        if score is not None:
            self.score = score

    @property
    def uuid(self):
        """Gets the uuid of this ScoreGet.  # noqa: E501


        :return: The uuid of this ScoreGet.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ScoreGet.


        :param uuid: The uuid of this ScoreGet.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def student(self):
        """Gets the student of this ScoreGet.  # noqa: E501


        :return: The student of this ScoreGet.  # noqa: E501
        :rtype: Student
        """
        return self._student

    @student.setter
    def student(self, student):
        """Sets the student of this ScoreGet.


        :param student: The student of this ScoreGet.  # noqa: E501
        :type: Student
        """

        self._student = student

    @property
    def period(self):
        """Gets the period of this ScoreGet.  # noqa: E501


        :return: The period of this ScoreGet.  # noqa: E501
        :rtype: PeriodGet
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this ScoreGet.


        :param period: The period of this ScoreGet.  # noqa: E501
        :type: PeriodGet
        """

        self._period = period

    @property
    def cohort(self):
        """Gets the cohort of this ScoreGet.  # noqa: E501


        :return: The cohort of this ScoreGet.  # noqa: E501
        :rtype: CohortGet
        """
        return self._cohort

    @cohort.setter
    def cohort(self, cohort):
        """Sets the cohort of this ScoreGet.


        :param cohort: The cohort of this ScoreGet.  # noqa: E501
        :type: CohortGet
        """

        self._cohort = cohort

    @property
    def excused(self):
        """Gets the excused of this ScoreGet.  # noqa: E501


        :return: The excused of this ScoreGet.  # noqa: E501
        :rtype: bool
        """
        return self._excused

    @excused.setter
    def excused(self, excused):
        """Sets the excused of this ScoreGet.


        :param excused: The excused of this ScoreGet.  # noqa: E501
        :type: bool
        """

        self._excused = excused

    @property
    def reason(self):
        """Gets the reason of this ScoreGet.  # noqa: E501


        :return: The reason of this ScoreGet.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ScoreGet.


        :param reason: The reason of this ScoreGet.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def score(self):
        """Gets the score of this ScoreGet.  # noqa: E501


        :return: The score of this ScoreGet.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ScoreGet.


        :param score: The score of this ScoreGet.  # noqa: E501
        :type: float
        """

        self._score = score

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScoreGet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
