# flake8: noqa

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.8
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.1.8"

# import ApiClient
from osis_internship_sdk.api_client import ApiClient

# import Configuration
from osis_internship_sdk.configuration import Configuration

# import exceptions
from osis_internship_sdk.exceptions import OpenApiException
from osis_internship_sdk.exceptions import ApiAttributeError
from osis_internship_sdk.exceptions import ApiTypeError
from osis_internship_sdk.exceptions import ApiValueError
from osis_internship_sdk.exceptions import ApiKeyError
from osis_internship_sdk.exceptions import ApiException
