# coding: utf-8

# flake8: noqa

"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    OpenAPI spec version: 1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from api.default_api import DefaultApi

# import ApiClient
from api_client import ApiClient
from configuration import Configuration
# import models into sdk package
from models.allocation_get import AllocationGet
from models.cohort_get import CohortGet
from models.country import Country
from models.internship_get import InternshipGet
from models.master_get import MasterGet
from models.organization_get import OrganizationGet
from models.paging import Paging
from models.period_get import PeriodGet
from models.person import Person
from models.specialty_get import SpecialtyGet
from models.student import Student
from models.student_affectation_get import StudentAffectationGet
from models.student_get import StudentGet
